= Operations Manual Build

This is a set of scripts and helper files for building WMUL-FM's Operations Manuals.

These scripts utilize multiple tools throughout the build process. Ruby is used to the majority of work. The Ruby Gem 
`WMUL Purple Mercury` handles the creation of needed symlinks, running `asciidoctor-reducer` on specified files, copying
specified files, and running `asciidoctor-pdf` or `asciidoctor-epub` as needed. 

The Java application, WMUL Green Mercury, handles gathering and rewriting the cross-references and anchors.

Antora is a NodeJS application that converts the AsciiDoc files into a web site.


== What to do with this repository

This repository needs to be cloned or downloaded into an adjacent folder to the `operations_manual_source` and 
`operations_manual_ui` folders.

[source,bash]
----
myfolder\operations_manual_source
myfolder\operations_manual_ui
myfolder\operations_manual_build
----

== Operating System

These instructions presume that you are working on an Ubuntu-based system. If you are using something else, you will 
have to translate these instructions into your system.

== Installing Prerequisites

=== Java and WMUL Green Mercury

. Install the Open JDK Java Runtime Environment version 25: `sudo apt install openjdk-25-jre`.

. `cd` into the `operations_manual_build` directory.

. Download the WMUL Green Mercury JAR with dependencies: `wget https://github.com/WMUL-FM/wmul_green_mercury/releases/download/v.0.0.4/green_mercury-0.0.4-jar-with-dependencies.jar`

=== RVM (Ruby Version Manager) and Ruby. 

. Install RVM: https://rvm.io/rvm/install
+
[source,bash]
----
gpg --keyserver keyserver.ubuntu.com --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
sudo apt install software-properties-common
sudo apt-add-repository -y ppa:rael-gc/rvm
sudo apt update
sudo apt install rvm
sudo usermod -a -G rvm $USER
echo 'source "/etc/profile.d/rvm.sh"' >> ~/.bashrc
----

. Reboot

. Verify RVM: `type rvm | head -n 1` 
+
The reponse should be: `rvm is a function`

. Install Ruby 3.4.9: `rvm install ruby-3.4.9`
+
This may take a few minutes, depending on the speed of your system.

. Verify Ruby: `ruby --version`

=== WMUL Purple Mercury

. cd into the `operations_manual_build` folder.

. Install WMUL Purple Mercury: `bundle install`

=== Node Version Manager, Node JS, and Antora

. Install NVM: `wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.4/install.sh | bash`

. Close and reopen your terminal window.

. Verify NVM: `nvm --version`

. Install a node.js LTS: `nvm install --lts`

. cd into the `operations_manual_build/web` folder.

. Install Antora: `node -e "fs.writeFileSync('package.json', '{}')" && npm i -D -E antora`

. Verify Antora: `npx antora -v`

== Setting Up the Symlinks

. cd into the `operations_manual_build` folder. 

. Run setup script: `./setup.sh` 
+
This runs all of the setup_* scripts, which create symlinks within the `../operations_manual_source` folder as needed 
for the build system.


== Edit Build Scripts

The final build script of each format, `antora_6_copy_to_final_destination.sh`, `epub_6_copy_to_final_destination.sh`, 
`pdf_7_copy_to_final_destination.sh`, and `standalone_7_copy_to_final_destination.sh` are configured for WMUL-FM's 
usage. You will need to set the `--destination_folder` in each one to be a folder accessible from your system.

== Building

. Build Antora: `./build_antora.sh`

. Build PDF: `./build_pdf.sh`

. Build ePub: `./build_epub.sh`

. Build Standalone: `./build_standalone.sh`


== Step by Step -- Setup

The setup steps should be executed first. They create important symlinks within the folder structure. (If you are from 
the Windows world, a symlink is like a folder shortcut.)

* `setup_1_create_symlinks_for_common_items.sh` Creates symlinks within the `/images` and `/attachments` folders.

* `setup_2_create_symlinks_for_antora.sh` Creates the symlinks from `/antora/modules/ROOT/images` to the appropriate 
subfolder inside `/images` and from `/antora/modules/ROOT/attachments` to the appropriate subfolder inside 
`/attachments` . The appropriate subfolders will depending on the selected color and license. 

* `setup_3_create_symlinks_for_pdf.sh` Creates the symlinks from `/pdf/images` to the appropriate subfolder inside 
`/images` and from `/pdf/attachments` to the appropriate subfolder inside `/attachments` . The appropriate subfolders 
will depending on the selected color and license. 

* `setup_4_create_symlinks_for_epub.sh` Creates the symlinks from `/epub/images` to the appropriate subfolder inside 
`/images` and from `/epub/attachments` to the appropriate subfolder inside `/attachments` . The appropriate subfolders 
will depending on the selected color and license. 

* `setup_5_create_symlinks_for_standalone.sh` Creates the symlinks from `/stanalone/images` to the appropriate 
subfolder inside `/images` and from `/standalone/attachments` to the appropriate subfolder inside `/attachments` . The 
appropriate subfolders will depending on the selected color and license. 

* `setup.sh` Conveniently runs the previous five commands sequentially.


== Step-By-Step - Antora

Antora is the software that creates the web version of the Operations Manual. 

* `antora_0_clean_build_folders.sh` Cleans out the build folders so that the build process has a clean slate at each 
step. Files that have been deleted or renamed in the `/src` folder might still exist in the build folders. 

** `../operations_manual_source/antora_intermediate/` Contains the output of step 1, which is used as the input of 
steps 3 and 4. 

** `../operations_manual_source/antora/modules/ROOT/pages/` Contains the output of step 4 and is used as the input of
step 5. 

** `../operations_manual_source/renders/web/` Contains the built webpage output of the antora command in step 5.

** `/mnt/T-Operations_Storage/Operations/ops_manual/` One of two folders to which the built webpage is copied. This 
folder is the mount point for an internal web server that is used when editing and debugging.

** `../operations_manual/web` The second folder to which the built webpage is copied. This folder is contained in a git 
repo. When a new version of the manual is ready to be published, this repo is committed and pushed to GitHub for the 
GitHub pages.

* `antora_1_build_source_for_antora.sh` Builds from the `/src` folder into the `/antora_intermediate` folder. All 
asciidoc include directives and ifdefs are resolved at this step. 

* `antora_2_copy_antora_static_folder.sh` Copies all of the items from the `/antora_static` folder into the `/antora` 
folder. These files include the antora `nav.adoc` file and the `antora.yml` playbook. 

* `antora_3_gather_anchors.sh` Runs green_mercury on the contents of `/antora_intermediate` and finds all of the anchors, 
`!!anchor name="anchor_name ref_text="Anchor Example on Page [page] of Volume I" /!!` , and places them into 
`anchors.yml`. 

* `antora_4_preprocess_files.sh` Runs green_mercury on the contents of `/antora_intermediate` and replaces all of the 
green_mercury anchors and cross-references with asciidoc anchors and cross-references. If the page numbers have been
input into `anchors.yml`, then those page numbers are embedded into the cross-references. The results are output to 
`/antora`.

* `antora_5_run_antora_command.sh` Runs the antora command from the `/web` folder in this repo against the `/antora` 
folder. The results are output to `/renders/web`.

* `antora_6_copy_to_final_destination.sh` Copies the contents of `/renders/web` to 
`/mnt/T-Operations_Storage/Operations/ops_manual/` and `../operations_manual/web`.

* `build_antora.sh` Conveniently runs the previous six commands sequentially.


== Step-By-Step - ePub

This sequence of commands results in ePub versions of the manual created by asciidoctor-epub3.

* `epub_0_clean_build_folders.sh` Cleans out the build folders so that the build process has a clean slate at each 
step. Files that have been deleted or renamed in the `/src` folder might still exist in the build folders. The final 
step re-creates the symlinks from `/epub/images` and `/epub/attachments` to the appropriate `/images` and 
`/attachments` subfolders.

** `../operations_manual_source/epub_intermediate/` Contains the output of step 1, which is used as the input of 
steps 3 and 4. 

** `../operations_manual_source/epub/` Contains the output of step 4 and is used as the input of step 5. 

** `../operations_manual_source/renders/epub/` Contains the built ePub output of step 5.

* `epub_1_build_source_for_epub.sh` Builds from the `/src` folder into the `/epub_intermediate` folder. All 
asciidoc include directives and ifdefs are resolved at this step. 

* `epub_2_copy_epub_static_folder.sh` Copies all of the items from the `/epub_static` folder into the `/epub` 
folder. These files are what build each actual volume of the epub by using asciidoc `include` commands to include the 
files in the `/epub` subfolders. 

* `epub_3_gather_anchors.sh` Runs green_mercury on the contents of `/epub_intermediate` and finds all of the anchors, 
`!!anchor name="anchor_name ref_text="Anchor Example on Page [page] of Volume I" /!!` , and places them into 
`anchors.yml`. 

* `epub_4_preprocess_files.sh` Runs green_mercury on the contents of `/epub_intermediate` and replaces all of the 
green_mercury anchors and cross-references with asciidoc anchors and cross-references. If the page numbers have been
input into `anchors.yml`, then those page numbers are embedded into the cross-references. The results are output to 
`/epub`.

* `epub_5_run_epub_command.sh` Runs the epub command on the files in the root `/epub` folder. These files should be the 
ones the came from `/epub_static`. The results are output to `/renders/epub`.

* `epub_6_copy_to_final_destination.sh` Copies the contents of `/renders/epub` to 
`/mnt/Z-Department_Storage/operations_manual/2026_revision/renders/`.

* `build_epub.sh` Conveniently runs the previous six commands sequentially.


== Step-By-Step - PDF

This sequence of commands results in ePub versions of the manual created by asciidoctor-pdf. It includes an extra step 
that is not needed for any of the other versions.

* `pdf_0_clean_build_folders.sh` Cleans out the build folders so that the build process has a clean slate at each 
step. Files that have been deleted or renamed in the `/src` folder might still exist in the build folders. The final 
step re-creates the symlinks from `/pdf/images` and `/pdf/attachments` to the appropriate `/images` and 
`/attachments` subfolders.

** `../operations_manual_source/pdf_intermediate/` Contains the output of step 1, which is used as the input of 
steps 4 and 5. 

** `../operations_manual_source/pdf/` Contains the output of step 5 and is used as the input of step 6. 

** `../operations_manual_source/renders/pdf/` Contains the built pdf output of step 6.

* `pdf_1_build_source_for_pdf.sh` Builds from the `/src` folder into the `/pdf_intermediate` folder. All 
asciidoc include directives and ifdefs are resolved at this step. 

* `pdf_2_copy_pdf_static_folder.sh` Copies all of the items from the `/pdf_static` and `/pdf_theme` folders into the 
`/pdf` folder. These files are what build each actual volume of the pdf by using asciidoc `include` commands to include 
the files in the `/pdf` subfolders. 

* `pdf_3_build_prebuild_asciidocs_to_pdf.sh` Certain asciidoc files are built to pdf separetely from the main document.
These are files that need a different theme applied. Examples include the chapter leading photo pages, the front matter,
the cover, and anything that is on letter head. 

* `pdf_4_gather_anchors.sh` Runs green_mercury on the contents of `/pdf_intermediate` and finds all of the anchors, 
`!!anchor name="anchor_name ref_text="Anchor Example on Page [page] of Volume I" /!!` , and places them into 
`anchors.yml`. 

* `pdf_5_preprocess_files.sh` Runs green_mercury on the contents of `/pdf_intermediate` and replaces all of the 
green_mercury anchors and cross-references with asciidoc anchors and cross-references. If the page numbers have been
input into `anchors.yml`, then those page numbers are embedded into the cross-references. The results are output to 
`/epub`.

* `pdf_6_run_pdf_command.sh` Runs the pdf command on the files in the root `/pdf` folder. These files should be the 
ones the came from `/pdf_static`. The results are output to `/renders/pdf`.

* `pdf_7_copy_to_final_destination.sh` Copies the contents of `/renders/pdf` to 
`/mnt/Z-Department_Storage/operations_manual/2026_revision/renders/`.

* `build_pdf.sh` Conveniently runs the previous seven commands sequentially.


== Step-By-Step - Standalone

This sequence of commands results in PDF versions of the small sections of the manual. These allow for sections of the
manual to be converted into handouts and wall posters. 

* `standalone_0_clean_build_folders.sh` Cleans out the build folders so that the build process has a clean slate at 
each step. Files that have been deleted or renamed in the `/src` folder might still exist in the build folders. The 
final step re-creates the symlinks from `/standalone/images` and `/standalone/attachments` to the appropriate 
`/images` and `/attachments` subfolders.

** `../operations_manual_source/standalone_intermediate/` Contains the output of step 1, which is used as the input of 
steps 3 and 4. 

** `../operations_manual_source/standalone/` Contains the output of step 4 and is used as the input of step 5. 

** `../operations_manual_source/renders/stanalone/` Contains the built PDF output of step 5.

* `standalone_1_build_source_for_standalone.sh` Builds from the `/src` folder into the `/standalone_intermediate` 
folder. All asciidoc include directives and ifdefs are resolved at this step. 

* `standalone_2_copy_standalone_static_folder.sh` Copies all of the items from the `/standalone_static` folder into 
the `/standalone` folder. These files are what build each individual pdf using asciidoc `include` commands to include 
the files in the `/standalone` subfolders. 

* (There is no standalone_3.) 

* `standalone_4_gather_anchors.sh` Runs green_mercury on the contents of `/standalone_intermediate` and finds all of 
the anchors, `!!anchor name="anchor_name ref_text="Anchor Example on Page [page] of Volume I" /!!` , and places them 
into `anchors.yml`. 

* `standalone_5_preprocess_files.sh` Runs green_mercury on the contents of `/standalone_intermediate` and replaces all 
of the green_mercury anchors and cross-references with asciidoc anchors and cross-references. If the page numbers have 
been input into `anchors.yml`, then those page numbers are embedded into the cross-references. The results are output 
to `/stanalone`.

* `standalone_6_run_pdf_command.sh` Runs the pdf command on the files in the root `/standalone` folder. These files 
should be the ones the came from `/standalone_static`. The results are output to `/renders/standalone`.

* `standalone_7_copy_to_final_destination.sh` Copies the contents of `/renders/standalone` to 
`/mnt/Z-Department_Storage/operations_manual/2026_revision/renders/`.

* `build_standalone.sh` Conveniently runs the previous six commands sequentially.
