site:
  title: WMUL-FM Operations Manual
  url: https://wmul-fm.github.io/operations_manual/
  start_page: operations_manual::01-introduction_volume_i/01-introduction_volume_i.adoc
content:
  sources:
  - url: ../../operations_manual_source/
    branches: main
    start_path: antora
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ../../operations_manual_ui
asciidoc:
  attributes:
    page-toclevels: 2
